### ISSUE TITLE
Suggestion to know when the sound is finished

### ISSUE THREAD

**Issue by AngeLoGa** [szmikler/playsound3#1]
Hello, I was trying to search for ways to reproduce sounds using Python and found the library playsound, and then found out that it was deprecated and you continued the work! Thanks for that.

I tested the module using the block argument, and saw that it doesn't return anything. Wouldn't it be interesting to return some kind of flag in order to know if the sound is still being reproduced? And also being able to stop it as well.

I'm not an expert on developing but I think this feature could be interesting. Would you appreciate a PR to test it out?

**Comment by szmikler** [comment]
Thanks for checking this out!

Sure, I'd appreciate a PR. You could just return the thread that is already being created. Then you would be able to check if sound is still playing by using thread's method `.is_alive()`.

Alternatively, there could be a wrapper object (e.g. `Sound`), but I think this would be overkill for this single functionality.

**Comment by szmikler** [comment]
Stopping a sound, however, might be difficult, as it is platform dependent. It should be possible to stop a sound that is played in a subprocess by sending SIGKILL, but not all platforms have it implemented this way. If you have an idea how to solve this (on all supported platforms), PR would be appreciated.

I would advice to fill a separate PR for the two functionalities. One PR for returning the Thread (or `Sound` object), another PR for adding the new functionality of stopping sounds.

**Comment by AngeLoGa** [comment]
Totally agree with the first point, I supposed that just returning the thread and using the method would be enough. Will work on it asap. About stopping it, the fast answer is no, I don't have an idea, but I can try to guess some way. Will comment any news about this.

**Comment by AngeLoGa** [comment]
Totally agree with the first point, I supposed that just returning the thread and using the method would be enough. Will work on it asap. About stopping it, the fast answer is no, I don't have an idea, but I can try to guess some way. Will comment any news about this.

**Comment by szmikler** [comment]
Non-blocking sounds will now return the thread object, so you can check whether the sound is still playing using thread's `is_alive()` method.
