### ISSUE TITLE
playsound3.AVAILABLE_BACKENDS - How to

### ISSUE THREAD

**Issue by roboticboyer** [szmikler/playsound3#4]
Please could you add an example how to use `playsound3.AVAILABLE_BACKENDS` and print the Available Backends

**Comment by szmikler** [comment]
Hey. `playsound3.AVAILABLE_BACKENDS` is a static array (of strings), therefore you can print the backends by printing the array:
```
print(playsound3.AVAILABLE_BACKENDS)
```

How to use a backend? Select one of the backends (here "BACKEND NAME") and use:
```
playsound3.playsound(SOUND_PATH, backend=BACKEND_NAME)
```

Let me know if that works for you.

**Comment by roboticboyer** [comment]
```
from playsound3 import playsound
print(playsound.AVAILABLE_BACKENDS)
```


there is the below error

```
print(playsound.AVAILABLE_BACKENDS)
AttributeError: 'function' object has no attribute 'AVAILABLE_BACKENDS'
```


I've also tried

```
print(playsound3.AVAILABLE_BACKENDS)
NameError: name 'playsound3' is not defined. Did you mean: 'playsound'?

```

**Comment by szmikler** [comment]
Hey.

So `playsound3` is the name of the library and `playsound` is the name of a function. `AVAILABLE_BACKENDS` is a list available in the library.

Therefore you would have to run
`from playsound3 import playsound, AVAILABLE_BACKENDS` or `import playsound3` and then use `playsound3.playsound(...)` and `playsound3.AVAILABLE_BACKENDS`.

Let me know if that works for you.

**Comment by roboticboyer** [comment]
Now is working!
Thank you
